import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <body className="vsc-initialized">
          <header>
            <nav className="navbar">
              <div className="container">
                <div className="navbar-brand">
                  <a
                    className="navbar-item is-flex is-flex-direction-column is-align-items-stretch"
                    href="/"
                  >
                    <h1 className="title is-3 mb-2">chichi-pui α版</h1>
                    <p className="is-size-7 has-text-dark">
                      「ちちんぷい！（ちちぷい）」AIイラスト専用の投稿サイト
                    </p>
                  </a>
                </div>
                <div className="navbar-end">
                  <div className="navbar-item">
                    <div className="buttons">
                      <a href="/login/?next=/" className="button is-light">
                        ログインする
                      </a>
                      <a href="/signup/?next=/" className="button is-primary">
                        ユーザー登録する（無料）
                      </a>
                    </div>
                  </div>
                </div>
              </div>
            </nav>
          </header>

          <div className="container">
            <div className="columns mt-2 px-5">
              <a
                href="https://twitter.com/chi2pui/status/1599700164335538177"
                className="column is-half is-offset-one-quarter"
                target="_blank"
                rel="noopener"
              >
                <img
                  src="https://storage.googleapis.com/chichipui/%E3%82%A4%E3%83%A9%E3%82%B9%E3%83%88%E4%BC%81%E7%94%BB_TOP%E3%83%8F%E3%83%8A%E3%83%BC_2.png"
                  alt="投稿企画_お題「こたつ」"
                />
              </a>
            </div>

            <div className="columns px-5">
              <div className="column is-half is-offset-one-quarter"></div>
            </div>

            <section className="section pt-0"></section>
          </div>

          <footer className="footer">
            <div className="content is-flex is-justify-content-center">
              <a
                href="https://closed-mistake-2ee.notion.site/chichi-pui-2fe1ec81fdb84a6cad2f81b4356fa8b9"
                className="is-size-7 mr-3"
              >
                利用規約
              </a>
              <a
                href="https://closed-mistake-2ee.notion.site/4c5db210068047c98a2ea865e2201982"
                className="is-size-7 mr-3"
              >
                個人情報保護方針
              </a>
              <a
                href="https://docs.google.com/forms/d/e/1FAIpQLSdnjd-k4cVbiOZTCBGo8QXPx87vwQANGXGjauGtm039GuEUPw/viewform"
                className="is-size-7 mr-3"
              >
                ご意見ボックス
              </a>
              <a
                href="https://closed-mistake-2ee.notion.site/3f0b25cf773641cb87de25503422fd13"
                className="is-size-7"
              >
                運営者情報
              </a>
            </div>
          </footer>

          <script src="/static/dist/js/home-index-cadbe07810e87065208a.85da000239c9.js"></script>
          <script src="/static/js/components/age-limit-confirm-modal.5b116513f604.js"></script>

          <table role="presentation" className="gstl_50 gssb_c">
            <tbody>
              <tr>
                <td className="gssb_f"></td>
                <td className="gssb_e"></td>
              </tr>
            </tbody>
          </table>
        </body>
      </main>
    </div>
  );
};

export default Home;
