import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Fig generated by Stable Diffusion</title>
        <meta name="description" content="Fig generated by Stable Diffusion" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <header>
          <nav className="navbar">
            <div className="container">
              <div className="navbar-brand">
                <a
                  className="navbar-item is-flex is-flex-direction-column is-align-items-stretch"
                  href="/"
                >
                  <h1 className="title is-3 mb-2">
                    Fig generated by Stable Diffusion
                  </h1>
                  <p className="is-size-7 has-text-dark">
                    Fig generated by Stable Diffusion
                  </p>
                </a>
              </div>
              <div className="navbar-end">
                <div className="navbar-item">
                  <div className="buttons">
                    <a href="/login/?next=/" className="button is-light">
                      Login
                    </a>
                    <a href="/signup/?next=/" className="button is-primary">
                      Signup
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </nav>
        </header>

        <div className="container">
          <div className="columns px-5">
            <div className="column is-half is-offset-one-quarter"></div>
          </div>

          <section className="section pt-0"></section>
        </div>

        <footer className="footer">
          <div className="content is-flex is-justify-content-center">
            <a href="" className="is-size-7 mr-3">
              利用規約
            </a>
            <a href="" className="is-size-7 mr-3">
              個人情報保護方針
            </a>
            <a href="" className="is-size-7 mr-3">
              ご意見ボックス
            </a>
            <a href="" className="is-size-7">
              運営者情報
            </a>
          </div>
        </footer>

        <table role="presentation" className="gstl_50 gssb_c">
          <tbody>
            <tr>
              <td className="gssb_f"></td>
              <td className="gssb_e"></td>
            </tr>
          </tbody>
        </table>
      </main>
    </div>
  );
};

export default Home;
