import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div className="bg-white text-black ">
      <Head>
        <title>Fig generated by Stable Diffusion</title>
        <meta name="description" content="Fig generated by Stable Diffusion" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-[#4A4A4A] leading-normal">
        <header>
          <nav className="items-stretch flex min-h-[3.25rem]  bg-white relative z-30">
            <div className="items-stretch flex min-h-14 w-full max-w-6xl grow mx-auto relative">
              <div className="ml-[-0.75rem] items-stretch flex shrink-0 min-h-[3.25rem] ">
                <a
                  className="cursor-pointer	flex items-stretch flex-col grow-0 shrink-0 py-[0.5rem] px-[0.75rem] relative"
                  href="/"
                >
                  <h1 className="title is-3 mb-2 text-4xl	">
                    Fig generated by Stable Diffusion
                  </h1>
                  <p className="is-size-7 has-text-dark text-xs">
                    Fig generated by Stable Diffusion
                  </p>
                </a>
              </div>
              <div className="justify-end ml-auto items-stretch flex">
                <div className=" items-center flex grow-0 shrink-0 leading-normal py-[0.5rem] px-[0.75rem] relative">
                  <div className="mb-[-0.5rem] items-center flex flex-wrap justify-start leading-normal">
                    <a
                      href="/login/?next=/"
                      className="mr-[0.5rem] mb-[0.5rem] bg-[#f5f5f5] border-transparent text-black/[.7] font-bold cursor-pointer pb-[calc(0.5em - 1px)] pl-[1em] pr-[1em] pt-[calc(0.5em - 1px)] text-center whitespace-nowrap select-none items-center rounded inline-flex text-base h-[2.5em] leading-normal relative align-top"
                    >
                      Login
                    </a>
                    <a
                      href="/signup/?next=/"
                      className="mr-[0.5rem] mb-[0.5rem] bg-[#FBFF00] border-transparent text-black/[.7] font-bold cursor-pointer pb-[calc(0.5em - 1px)] pl-[1em] pr-[1em] pt-[calc(0.5em - 1px)] text-center whitespace-nowrap select-none items-center rounded inline-flex text-base h-[2.5em] leading-normal relative align-top"
                    >
                      Sign Up (free)
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </nav>
        </header>

        <div className="max-w-6xl mx-auto relative w-auto">
          <section className="pt-0 px-[3rem] ">
            <div id="app">
              <div className="pb-[1.5rem]">
                <h2 className="text-2xl mb-[1.5rem] text-[#363636] font-semibold leading-[1.125]">
                  Recommended
                </h2>
                <div className="flex flex-wrap mb-[-0.75rem] mt-[-0.75rem] mx-[-0.75rem]">
                  <div className="flex-none w-1/5 block	p-[0.75rem]">
                    <a href="/posts/fd31d445-9407-486f-a361-6a0368762950/">
                      <div>
                        <figure className="block relative">
                          <img
                            src="https://picsum.photos/id/181/400/400.jpg"
                            alt="吸飴鬼お嬢"
                            className="is-radius-2"
                            loading="lazy"
                          />
                        </figure>
                      </div>
                      <div>
                        <h3 className="text-base overflow-hidden text-ellipsis whitespace-nowrap my-[0.5rem] font-semibold">
                          吸飴鬼お嬢
                        </h3>
                        <div className="flex items-center ">
                          <div>
                            <figure className="h-[24px] w-[24px] mr-[0.25rem] block relative ">
                              <img
                                src="https://pbs.twimg.com/profile_images/1334457292830326787/_5-975oq_normal.png"
                                className="rounded-full"
                                loading="lazy"
                              />
                            </figure>
                          </div>
                          <p className="text-[0.75rem]">
                            シルエットさくら
                          </p>
                        </div>
                      </div>
                    </a>
                  </div>
                  <div className="flex-none w-1/5 block	p-[0.75rem]">
                    <a href="/posts/fd31d445-9407-486f-a361-6a0368762950/">
                      <div>
                        <figure className="block relative">
                          <img
                            src="https://picsum.photos/id/181/400/400.jpg"
                            alt="吸飴鬼お嬢"
                            className="is-radius-2"
                            loading="lazy"
                          />
                        </figure>
                      </div>
                      <div>
                        <h3 className="text-base overflow-hidden text-ellipsis whitespace-nowrap my-[0.5rem] font-semibold">
                          吸飴鬼お嬢
                        </h3>
                        <div className="flex items-center ">
                          <div>
                            <figure className="h-[24px] w-[24px] mr-[0.25rem] block relative ">
                              <img
                                src="https://pbs.twimg.com/profile_images/1334457292830326787/_5-975oq_normal.png"
                                className="rounded-full"
                                loading="lazy"
                              />
                            </figure>
                          </div>
                          <p className="text-[0.75rem]">
                            シルエットさくら
                          </p>
                        </div>
                      </div>
                    </a>
                  </div>
                  <div className="flex-none w-1/5 block	p-[0.75rem]">
                    <a href="/posts/fd31d445-9407-486f-a361-6a0368762950/">
                      <div>
                        <figure className="block relative">
                          <img
                            src="https://picsum.photos/id/181/400/400.jpg"
                            alt="吸飴鬼お嬢"
                            className="is-radius-2"
                            loading="lazy"
                          />
                        </figure>
                      </div>
                      <div>
                        <h3 className="text-base overflow-hidden text-ellipsis whitespace-nowrap my-[0.5rem] font-semibold">
                          吸飴鬼お嬢
                        </h3>
                        <div className="flex items-center ">
                          <div>
                            <figure className="h-[24px] w-[24px] mr-[0.25rem] block relative ">
                              <img
                                src="https://pbs.twimg.com/profile_images/1334457292830326787/_5-975oq_normal.png"
                                className="rounded-full"
                                loading="lazy"
                              />
                            </figure>
                          </div>
                          <p className="text-[0.75rem]">
                            シルエットさくら
                          </p>
                        </div>
                      </div>
                    </a>
                  </div>
                  <div className="flex-none w-1/5 block	p-[0.75rem]">
                    <a href="/posts/fd31d445-9407-486f-a361-6a0368762950/">
                      <div>
                        <figure className="block relative">
                          <img
                            src="https://picsum.photos/id/181/400/400.jpg"
                            alt="吸飴鬼お嬢"
                            className="is-radius-2"
                            loading="lazy"
                          />
                        </figure>
                      </div>
                      <div>
                        <h3 className="text-base overflow-hidden text-ellipsis whitespace-nowrap my-[0.5rem] font-semibold">
                          吸飴鬼お嬢
                        </h3>
                        <div className="flex items-center ">
                          <div>
                            <figure className="h-[24px] w-[24px] mr-[0.25rem] block relative ">
                              <img
                                src="https://pbs.twimg.com/profile_images/1334457292830326787/_5-975oq_normal.png"
                                className="rounded-full"
                                loading="lazy"
                              />
                            </figure>
                          </div>
                          <p className="text-[0.75rem]">
                            シルエットさくら
                          </p>
                        </div>
                      </div>
                    </a>
                  </div>
                  <div className="flex-none w-1/5 block	p-[0.75rem]">
                    <a href="/posts/fd31d445-9407-486f-a361-6a0368762950/">
                      <div>
                        <figure className="block relative">
                          <img
                            src="https://picsum.photos/id/181/400/400.jpg"
                            alt="吸飴鬼お嬢"
                            className="is-radius-2"
                            loading="lazy"
                          />
                        </figure>
                      </div>
                      <div>
                        <h3 className="text-base overflow-hidden text-ellipsis whitespace-nowrap my-[0.5rem] font-semibold">
                          吸飴鬼お嬢
                        </h3>
                        <div className="flex items-center ">
                          <div>
                            <figure className="h-[24px] w-[24px] mr-[0.25rem] block relative ">
                              <img
                                src="https://pbs.twimg.com/profile_images/1334457292830326787/_5-975oq_normal.png"
                                className="rounded-full"
                                loading="lazy"
                              />
                            </figure>
                          </div>
                          <p className="text-[0.75rem]">
                            シルエットさくら
                          </p>
                        </div>
                      </div>
                    </a>
                  </div>
                </div>
              </div>
              <div className="pb-[1.5rem]">
                <h2 className="text-2xl mb-[1.5rem] text-[#363636] font-semibold leading-[1.125]">
                  Recommended
                </h2>
                <div className="flex flex-wrap mb-[-0.75rem] mt-[-0.75rem] mx-[-0.75rem]">
                  <div className="flex-none w-1/5 block	p-[0.75rem]">
                    <a href="/posts/fd31d445-9407-486f-a361-6a0368762950/">
                      <div>
                        <figure className="block relative">
                          <img
                            src="https://picsum.photos/id/181/400/400.jpg"
                            alt="吸飴鬼お嬢"
                            className="is-radius-2"
                            loading="lazy"
                          />
                        </figure>
                      </div>
                      <div>
                        <h3 className="text-base overflow-hidden text-ellipsis whitespace-nowrap my-[0.5rem] font-semibold">
                          吸飴鬼お嬢
                        </h3>
                        <div className="flex items-center ">
                          <div>
                            <figure className="h-[24px] w-[24px] mr-[0.25rem] block relative ">
                              <img
                                src="https://pbs.twimg.com/profile_images/1334457292830326787/_5-975oq_normal.png"
                                className="rounded-full"
                                loading="lazy"
                              />
                            </figure>
                          </div>
                          <p className="text-[0.75rem]">
                            シルエットさくら
                          </p>
                        </div>
                      </div>
                    </a>
                  </div>
                  <div className="flex-none w-1/5 block	p-[0.75rem]">
                    <a href="/posts/fd31d445-9407-486f-a361-6a0368762950/">
                      <div>
                        <figure className="block relative">
                          <img
                            src="https://picsum.photos/id/181/400/400.jpg"
                            alt="吸飴鬼お嬢"
                            className="is-radius-2"
                            loading="lazy"
                          />
                        </figure>
                      </div>
                      <div>
                        <h3 className="text-base overflow-hidden text-ellipsis whitespace-nowrap my-[0.5rem] font-semibold">
                          吸飴鬼お嬢
                        </h3>
                        <div className="flex items-center ">
                          <div>
                            <figure className="h-[24px] w-[24px] mr-[0.25rem] block relative ">
                              <img
                                src="https://pbs.twimg.com/profile_images/1334457292830326787/_5-975oq_normal.png"
                                className="rounded-full"
                                loading="lazy"
                              />
                            </figure>
                          </div>
                          <p className="text-[0.75rem]">
                            シルエットさくら
                          </p>
                        </div>
                      </div>
                    </a>
                  </div>
                  <div className="flex-none w-1/5 block	p-[0.75rem]">
                    <a href="/posts/fd31d445-9407-486f-a361-6a0368762950/">
                      <div>
                        <figure className="block relative">
                          <img
                            src="https://picsum.photos/id/181/400/400.jpg"
                            alt="吸飴鬼お嬢"
                            className="is-radius-2"
                            loading="lazy"
                          />
                        </figure>
                      </div>
                      <div>
                        <h3 className="text-base overflow-hidden text-ellipsis whitespace-nowrap my-[0.5rem] font-semibold">
                          吸飴鬼お嬢
                        </h3>
                        <div className="flex items-center ">
                          <div>
                            <figure className="h-[24px] w-[24px] mr-[0.25rem] block relative ">
                              <img
                                src="https://pbs.twimg.com/profile_images/1334457292830326787/_5-975oq_normal.png"
                                className="rounded-full"
                                loading="lazy"
                              />
                            </figure>
                          </div>
                          <p className="text-[0.75rem]">
                            シルエットさくら
                          </p>
                        </div>
                      </div>
                    </a>
                  </div>
                  <div className="flex-none w-1/5 block	p-[0.75rem]">
                    <a href="/posts/fd31d445-9407-486f-a361-6a0368762950/">
                      <div>
                        <figure className="block relative">
                          <img
                            src="https://picsum.photos/id/181/400/400.jpg"
                            alt="吸飴鬼お嬢"
                            className="is-radius-2"
                            loading="lazy"
                          />
                        </figure>
                      </div>
                      <div>
                        <h3 className="text-base overflow-hidden text-ellipsis whitespace-nowrap my-[0.5rem] font-semibold">
                          吸飴鬼お嬢
                        </h3>
                        <div className="flex items-center ">
                          <div>
                            <figure className="h-[24px] w-[24px] mr-[0.25rem] block relative ">
                              <img
                                src="https://pbs.twimg.com/profile_images/1334457292830326787/_5-975oq_normal.png"
                                className="rounded-full"
                                loading="lazy"
                              />
                            </figure>
                          </div>
                          <p className="text-[0.75rem]">
                            シルエットさくら
                          </p>
                        </div>
                      </div>
                    </a>
                  </div>
                  <div className="flex-none w-1/5 block	p-[0.75rem]">
                    <a href="/posts/fd31d445-9407-486f-a361-6a0368762950/">
                      <div>
                        <figure className="block relative">
                          <img
                            src="https://picsum.photos/id/181/400/400.jpg"
                            alt="吸飴鬼お嬢"
                            className="is-radius-2"
                            loading="lazy"
                          />
                        </figure>
                      </div>
                      <div>
                        <h3 className="text-base overflow-hidden text-ellipsis whitespace-nowrap my-[0.5rem] font-semibold">
                          吸飴鬼お嬢
                        </h3>
                        <div className="flex items-center ">
                          <div>
                            <figure className="h-[24px] w-[24px] mr-[0.25rem] block relative ">
                              <img
                                src="https://pbs.twimg.com/profile_images/1334457292830326787/_5-975oq_normal.png"
                                className="rounded-full"
                                loading="lazy"
                              />
                            </figure>
                          </div>
                          <p className="text-[0.75rem]">
                            シルエットさくら
                          </p>
                        </div>
                      </div>
                    </a>
                  </div>
                </div>
              </div>
              <div className="pb-[1.5rem]">
                <h2 className="text-2xl mb-[1.5rem] text-[#363636] font-semibold leading-[1.125]">
                  Recommended
                </h2>
                <div className="flex flex-wrap mb-[-0.75rem] mt-[-0.75rem] mx-[-0.75rem]">
                  <div className="flex-none w-1/5 block	p-[0.75rem]">
                    <a href="/posts/fd31d445-9407-486f-a361-6a0368762950/">
                      <div>
                        <figure className="block relative">
                          <img
                            src="https://picsum.photos/id/181/400/400.jpg"
                            alt="吸飴鬼お嬢"
                            className="is-radius-2"
                            loading="lazy"
                          />
                        </figure>
                      </div>
                      <div>
                        <h3 className="text-base overflow-hidden text-ellipsis whitespace-nowrap my-[0.5rem] font-semibold">
                          吸飴鬼お嬢
                        </h3>
                        <div className="flex items-center ">
                          <div>
                            <figure className="h-[24px] w-[24px] mr-[0.25rem] block relative ">
                              <img
                                src="https://pbs.twimg.com/profile_images/1334457292830326787/_5-975oq_normal.png"
                                className="rounded-full"
                                loading="lazy"
                              />
                            </figure>
                          </div>
                          <p className="text-[0.75rem]">
                            シルエットさくら
                          </p>
                        </div>
                      </div>
                    </a>
                  </div>
                  <div className="flex-none w-1/5 block	p-[0.75rem]">
                    <a href="/posts/fd31d445-9407-486f-a361-6a0368762950/">
                      <div>
                        <figure className="block relative">
                          <img
                            src="https://picsum.photos/id/181/400/400.jpg"
                            alt="吸飴鬼お嬢"
                            className="is-radius-2"
                            loading="lazy"
                          />
                        </figure>
                      </div>
                      <div>
                        <h3 className="text-base overflow-hidden text-ellipsis whitespace-nowrap my-[0.5rem] font-semibold">
                          吸飴鬼お嬢
                        </h3>
                        <div className="flex items-center ">
                          <div>
                            <figure className="h-[24px] w-[24px] mr-[0.25rem] block relative ">
                              <img
                                src="https://pbs.twimg.com/profile_images/1334457292830326787/_5-975oq_normal.png"
                                className="rounded-full"
                                loading="lazy"
                              />
                            </figure>
                          </div>
                          <p className="text-[0.75rem]">
                            シルエットさくら
                          </p>
                        </div>
                      </div>
                    </a>
                  </div>
                  <div className="flex-none w-1/5 block	p-[0.75rem]">
                    <a href="/posts/fd31d445-9407-486f-a361-6a0368762950/">
                      <div>
                        <figure className="block relative">
                          <img
                            src="https://picsum.photos/id/181/400/400.jpg"
                            alt="吸飴鬼お嬢"
                            className="is-radius-2"
                            loading="lazy"
                          />
                        </figure>
                      </div>
                      <div>
                        <h3 className="text-base overflow-hidden text-ellipsis whitespace-nowrap my-[0.5rem] font-semibold">
                          吸飴鬼お嬢
                        </h3>
                        <div className="flex items-center ">
                          <div>
                            <figure className="h-[24px] w-[24px] mr-[0.25rem] block relative ">
                              <img
                                src="https://pbs.twimg.com/profile_images/1334457292830326787/_5-975oq_normal.png"
                                className="rounded-full"
                                loading="lazy"
                              />
                            </figure>
                          </div>
                          <p className="text-[0.75rem]">
                            シルエットさくら
                          </p>
                        </div>
                      </div>
                    </a>
                  </div>
                  <div className="flex-none w-1/5 block	p-[0.75rem]">
                    <a href="/posts/fd31d445-9407-486f-a361-6a0368762950/">
                      <div>
                        <figure className="block relative">
                          <img
                            src="https://picsum.photos/id/181/400/400.jpg"
                            alt="吸飴鬼お嬢"
                            className="is-radius-2"
                            loading="lazy"
                          />
                        </figure>
                      </div>
                      <div>
                        <h3 className="text-base overflow-hidden text-ellipsis whitespace-nowrap my-[0.5rem] font-semibold">
                          吸飴鬼お嬢
                        </h3>
                        <div className="flex items-center ">
                          <div>
                            <figure className="h-[24px] w-[24px] mr-[0.25rem] block relative ">
                              <img
                                src="https://pbs.twimg.com/profile_images/1334457292830326787/_5-975oq_normal.png"
                                className="rounded-full"
                                loading="lazy"
                              />
                            </figure>
                          </div>
                          <p className="text-[0.75rem]">
                            シルエットさくら
                          </p>
                        </div>
                      </div>
                    </a>
                  </div>
                  <div className="flex-none w-1/5 block	p-[0.75rem]">
                    <a href="/posts/fd31d445-9407-486f-a361-6a0368762950/">
                      <div>
                        <figure className="block relative">
                          <img
                            src="https://picsum.photos/id/181/400/400.jpg"
                            alt="吸飴鬼お嬢"
                            className="is-radius-2"
                            loading="lazy"
                          />
                        </figure>
                      </div>
                      <div>
                        <h3 className="text-base overflow-hidden text-ellipsis whitespace-nowrap my-[0.5rem] font-semibold">
                          吸飴鬼お嬢
                        </h3>
                        <div className="flex items-center ">
                          <div>
                            <figure className="h-[24px] w-[24px] mr-[0.25rem] block relative ">
                              <img
                                src="https://pbs.twimg.com/profile_images/1334457292830326787/_5-975oq_normal.png"
                                className="rounded-full"
                                loading="lazy"
                              />
                            </figure>
                          </div>
                          <p className="text-[0.75rem]">
                            シルエットさくら
                          </p>
                        </div>
                      </div>
                    </a>
                  </div>
                </div>
              </div>
              <div className="pb-5"></div>
              <div className="pb-5"></div>
              <div className="pb-5"></div>
            </div>
          </section>
        </div>

        <footer className="bg-[#fafafa] pt-[3rem] px=[1.5rem] pb-[6rem]">
          <div className="flex justify-center">
            <a href="" className="text-[0.75rem] mr-[0.75rem] text-[#485fc7] cursor-pointer no-underline">
              利用規約
            </a>
            <a href="" className="text-[0.75rem] mr-[0.75rem] text-[#485fc7] cursor-pointer no-underline">
              個人情報保護方針
            </a>
            <a href="" className="text-[0.75rem] mr-[0.75rem] text-[#485fc7] cursor-pointer no-underline">
              Feedback
            </a>
            <a href="" className="text-[0.75rem] mr-[0.75rem] text-[#485fc7] cursor-pointer no-underline">
              Author
            </a>
          </div>
        </footer>

        <table role="presentation" className="gstl_50 gssb_c">
          <tbody>
            <tr>
              <td className="gssb_f"></td>
              <td className="gssb_e"></td>
            </tr>
          </tbody>
        </table>
      </main>
    </div>
  );
};

export default Home;
